upstream django {
    server web:8000;
}

# HTTP → HTTPS (кроме challenge)
server {
    listen 80;
    server_name _;

    # Certbot challenge оставляем на HTTP
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Всё остальное — на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS
server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/letsencrypt/live/habitracker.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/habitracker.duckdns.org/privkey.pem;

    # Статика
    location /static/ {
        alias /app/staticfiles/;
    }

    # Django
    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
