# Generated by Django 6.1.1 on 2026-09-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_habit_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='target',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
